rules:
  default:
    protection:
      required_pull_request_reviews: null
      #  required_approving_review_count: 0
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/jenkins/pr-head
