rules:
  default:
    protection:
      required_pull_request_reviews: 
        required_approving_review_count: 
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/jenkins/pr-head
